### ISSUE TITLE
Fix listing with no reader on FreeBSD

### ISSUE THREAD

**Issue by martinpaljak** [martinpaljak/apdu4j#2]
`# java -jar apdu4j.jar -ldv
# Using sun.security.smartcardio.SunPCSC - SunPCSC version 1.7
# sun.security.smartcardio.library=/usr/local/lib/libpcsclite.so
Exception in thread "main" javax.smartcardio.CardException: list() failed
	at sun.security.smartcardio.PCSCTerminals.list(PCSCTerminals.java:126)
	at javax.smartcardio.CardTerminals.list(CardTerminals.java:72)
	at apdu4j.SCTool.main(SCTool.java:175)
Caused by: sun.security.smartcardio.PCSCException: SCARD_E_NO_READERS_AVAILABLE
	at sun.security.smartcardio.PCSC.SCardListReaders(Native Method)
	at sun.security.smartcardio.PCSCTerminals.list(PCSCTerminals.java:80)
	... 2 more`

**Comment by martinpaljak** [comment]
Nice messages on all tested platforms a norm for SC tools
