### ISSUE TITLE
Fix jnasmartcardio and apdu4j for use with M1 applet chips

### ISSUE THREAD

**Issue by martinpaljak** [martinpaljak/apdu4j#51]
From https://github.com/martinpaljak/GlobalPlatformPro/issues/260

**Comment by kategray** [comment]
For completeness, here's the [expected] error with the latest release:

```kate@Kates-MacBook-Air ~ % java -jar ~/Downloads/apdu4j.jar -v -d -l
java.lang.IllegalStateException: jnasmartcardio not bundled
	at apdu4j.TerminalManager.getTerminalFactory(TerminalManager.java:123)
	at apdu4j.SCTool.getTerminalFactory(SCTool.java:425)
	at apdu4j.SCTool.listReaders(SCTool.java:105)
	at apdu4j.SCTool.call(SCTool.java:379)
	at apdu4j.SCTool.call(SCTool.java:50)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at apdu4j.SCTool.main(SCTool.java:366)
```

**Comment by martinpaljak** [comment]
Fixed in https://github.com/martinpaljak/apdu4j/releases/v21.04.01
